/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/Alert.vue')['default']
    AreaList: typeof import('./src/components/layout/AreaList.vue')['default']
    Background: typeof import('./src/components/ui/Background.vue')['default']
    BorderBackground: typeof import('./src/components/ui/BorderBackground.vue')['default']
    Calendar: typeof import('./src/components/ui/Calendar/index.vue')['default']
    CBody: typeof import('./src/components/ui/Calendar/CBody.vue')['default']
    CHeader: typeof import('./src/components/ui/Calendar/CHeader.vue')['default']
    Code: typeof import('./src/components/layout/Code.vue')['default']
    ColorPicker: typeof import('./src/components/ui/ColorPicker.vue')['default']
    ConfettiCanvas: typeof import('./src/components/ui/ConfettiCanvas.vue')['default']
    copy: typeof import('./src/components/layout/ScratchySearchInput copy.vue')['default']
    CTable: typeof import('./src/components/ui/CTable.vue')['default']
    CustomMapboxPopup: typeof import('./src/components/ui/CustomMapboxPopup.vue')['default']
    GeneratorBySVG: typeof import('./src/components/GeneratorBySVG.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HighlightCode: typeof import('./src/components/ui/HighlightCode.vue')['default']
    HolidaysCalendar: typeof import('./src/components/layout/HolidaysCalendar.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    MainMap: typeof import('./src/components/layout/MainMap.vue')['default']
    MapboxMap: typeof import('./src/components/MapboxMap.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    MonthHoliday: typeof import('./src/components/layout/MonthHoliday.vue')['default']
    Options: typeof import('./src/components/layout/Options.vue')['default']
    Preview: typeof import('./src/components/layout/Preview.vue')['default']
    RangeBar: typeof import('./src/components/ui/RangeBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouterWrapper: typeof import('./src/components/ui/RouterWrapper.vue')['default']
    ScratchyBackground: typeof import('./src/components/ui/ScratchyBackground.vue')['default']
    ScratchyBorder: typeof import('./src/components/ui/ScratchyBorder.vue')['default']
    ScratchyCircle: typeof import('./src/components/ui/ScratchyCircle.vue')['default']
    ScratchySearchInput: typeof import('./src/components/layout/ScratchySearchInput.vue')['default']
    ScratchyText: typeof import('./src/components/ui/ScratchyText.vue')['default']
    SearchInput: typeof import('./src/components/layout/SearchInput.vue')['default']
    TextareaCode: typeof import('./src/components/ui/TextareaCode.vue')['default']
    Tools: typeof import('./src/components/layout/Tools.vue')['default']
    WeekName: typeof import('./src/components/ui/Calendar/WeekName.vue')['default']
  }
}
