/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/Alert.vue')['default']
    AreaList: typeof import('./src/components/layout/AreaList.vue')['default']
    Background: typeof import('./src/components/ui/Background.vue')['default']
    BorderBackground: typeof import('./src/components/ui/BorderBackground.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Code: typeof import('./src/components/layout/Code.vue')['default']
    ColorPicker: typeof import('./src/components/ui/ColorPicker.vue')['default']
    ConfettiCanvas: typeof import('./src/components/ui/ConfettiCanvas.vue')['default']
    GeneratorBySVG: typeof import('./src/components/GeneratorBySVG.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HighlightCode: typeof import('./src/components/ui/HighlightCode.vue')['default']
    HolidaysCalendar: typeof import('./src/components/layout/HolidaysCalendar.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    MainMap: typeof import('./src/components/layout/MainMap.vue')['default']
    MapboxMap: typeof import('./src/components/MapboxMap.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    Options: typeof import('./src/components/layout/Options.vue')['default']
    Preview: typeof import('./src/components/layout/Preview.vue')['default']
    RangeBar: typeof import('./src/components/ui/RangeBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScratchyCircle: typeof import('./src/components/ui/ScratchyCircle.vue')['default']
    ScratchyLogo: typeof import('./src/components/ui/ScratchyLogo.vue')['default']
    ScratchyText: typeof import('./src/components/ui/ScratchyText.vue')['default']
    TextareaCode: typeof import('./src/components/ui/TextareaCode.vue')['default']
    Tools: typeof import('./src/components/layout/Tools.vue')['default']
  }
}
